// Ligue 1
const ligue1 = {
  id: 'ligue_1',
  name: 'Ligue 1',
  country: 'France',
  emoji: '🇫🇷',
  teams: [
    {
      id: 'psg',
      name: 'Paris Saint-Germain',
      shortName: 'PSG',
      emoji: '🔵🔴',
      stadium: 'Parc des Princes',
      manager: 'Luis Enrique',
      budget: 300000000,
      players: [
        { id: 'donnarumma', name: 'Gianluigi Donnarumma', position: 'GK', nationality: 'Italy', age: 25, overall: 89, wage: 300000 },
        { id: 'hakimi', name: 'Achraf Hakimi', position: 'RB', nationality: 'Morocco', age: 26, overall: 87, wage: 250000 },
        { id: 'marquinhos', name: 'Marquinhos', position: 'CB', nationality: 'Brazil', age: 30, overall: 86, wage: 200000 },
        { id: 'skriniar', name: 'Milan Škriniar', position: 'CB', nationality: 'Slovakia', age: 29, overall: 83, wage: 200000 },
        { id: 'nuno_m', name: 'Nuno Mendes', position: 'LB', nationality: 'Portugal', age: 22, overall: 84, wage: 150000 },
        { id: 'vitinha_p', name: 'Vitinha', position: 'CM', nationality: 'Portugal', age: 24, overall: 83, wage: 150000 },
        { id: 'ugarte', name: 'Manuel Ugarte', position: 'CM', nationality: 'Uruguay', age: 23, overall: 81, wage: 120000 },
        { id: 'fabian_r', name: 'Fabián Ruiz', position: 'CM', nationality: 'Spain', age: 28, overall: 83, wage: 150000 },
        { id: 'dembele_o', name: 'Ousmane Dembélé', position: 'RW', nationality: 'France', age: 27, overall: 85, wage: 200000 },
        { id: 'gonçalo_r', name: 'Gonçalo Ramos', position: 'ST', nationality: 'Portugal', age: 23, overall: 81, wage: 150000 },
        { id: 'barcola', name: 'Bradley Barcola', position: 'LW', nationality: 'France', age: 22, overall: 80, wage: 100000 },
        { id: 'asensio', name: 'Marco Asensio', position: 'CAM', nationality: 'Spain', age: 28, overall: 80, wage: 150000 },
        { id: 'lee_k', name: 'Kang-in Lee', position: 'CAM', nationality: 'South Korea', age: 23, overall: 79, wage: 100000 },
        { id: 'hernandez_l', name: 'Lucas Hernández', position: 'CB', nationality: 'France', age: 28, overall: 81, wage: 200000 },
        { id: 'zaire_e', name: 'Zaire-Emery', position: 'CM', nationality: 'France', age: 18, overall: 78, wage: 50000 },
        { id: 'safonov', name: 'Matvei Safonov', position: 'GK', nationality: 'Russia', age: 25, overall: 78, wage: 80000 },
        { id: 'beraldo', name: 'Lucas Beraldo', position: 'CB', nationality: 'Brazil', age: 20, overall: 74, wage: 40000 },
        { id: 'mukiele', name: 'Nordi Mukiele', position: 'RB', nationality: 'France', age: 26, overall: 77, wage: 80000 },
        { id: 'del_cerro', name: 'Ethan Mbappé', position: 'CM', nationality: 'France', age: 18, overall: 68, wage: 15000 },
        { id: 'soler', name: 'Carlos Soler', position: 'CM', nationality: 'Spain', age: 27, overall: 78, wage: 100000 },
        { id: 'fullkrug_2', name: 'Randal Kolo Muani', position: 'ST', nationality: 'France', age: 25, overall: 80, wage: 150000 },
      ]
    },
    {
      id: 'monaco',
      name: 'AS Monaco',
      shortName: 'Monaco',
      emoji: '🔴⚪',
      stadium: 'Stade Louis II',
      manager: 'Adi Hütter',
      budget: 80000000,
      players: [
        { id: 'majecki', name: 'Radosław Majecki', position: 'GK', nationality: 'Poland', age: 24, overall: 76, wage: 60000 },
        { id: 'vanderson', name: 'Vanderson', position: 'RB', nationality: 'Brazil', age: 23, overall: 77, wage: 70000 },
        { id: 'singo', name: 'Wilfried Singo', position: 'RB', nationality: 'Ivory Coast', age: 23, overall: 77, wage: 70000 },
        { id: 'maripan', name: 'Guillermo Maripán', position: 'CB', nationality: 'Chile', age: 30, overall: 77, wage: 80000 },
        { id: 'disasi_a', name: 'Axel Disasi', position: 'CB', nationality: 'France', age: 26, overall: 78, wage: 100000 },
        { id: 'camara', name: 'Mohamed Camara', position: 'CM', nationality: 'Mali', age: 24, overall: 78, wage: 80000 },
        { id: 'fofana', name: 'Youssouf Fofana', position: 'CM', nationality: 'France', age: 25, overall: 79, wage: 100000 },
        { id: 'golovin', name: 'Aleksandr Golovin', position: 'CM', nationality: 'Russia', age: 28, overall: 78, wage: 100000 },
        { id: 'akliouche', name: 'Maghnes Akliouche', position: 'CAM', nationality: 'France', age: 22, overall: 76, wage: 50000 },
        { id: 'ben_yedder', name: 'Wissam Ben Yedder', position: 'ST', nationality: 'France', age: 34, overall: 80, wage: 200000 },
        { id: 'embolo', name: 'Breel Embolo', position: 'ST', nationality: 'Switzerland', age: 27, overall: 77, wage: 100000 },
        { id: 'minamino', name: 'Takumi Minamino', position: 'LW', nationality: 'Japan', age: 29, overall: 76, wage: 80000 },
        { id: 'caio_h', name: 'Caio Henrique', position: 'LB', nationality: 'Brazil', age: 26, overall: 78, wage: 80000 },
        { id: 'jakobs', name: 'Ismail Jakobs', position: 'LB', nationality: 'Germany', age: 24, overall: 74, wage: 50000 },
        { id: 'diatta', name: 'Krepin Diatta', position: 'RW', nationality: 'Senegal', age: 24, overall: 76, wage: 60000 },
        { id: 'boadu', name: 'Myron Boadu', position: 'ST', nationality: 'Netherlands', age: 23, overall: 73, wage: 50000 },
        { id: 'zakaria', name: 'Denis Zakaria', position: 'CM', nationality: 'Switzerland', age: 27, overall: 77, wage: 100000 },
        { id: 'balogun_f', name: 'Folarin Balogun', position: 'ST', nationality: 'USA', age: 23, overall: 77, wage: 80000 },
        { id: 'henrique_d', name: 'Denis Alibec', position: 'ST', nationality: 'Romania', age: 33, overall: 72, wage: 40000 },
        { id: 'nubel', name: 'Alexander Nübel', position: 'GK', nationality: 'Germany', age: 27, overall: 80, wage: 80000 },
        { id: 'gelson', name: 'Gelson Martins', position: 'RW', nationality: 'Portugal', age: 29, overall: 77, wage: 100000 },
      ]
    },
  ]
};

// Eredivisie (Netherlands)
const eredivisie = {
  id: 'eredivisie',
  name: 'Eredivisie',
  country: 'Netherlands',
  emoji: '🇳🇱',
  teams: [
    {
      id: 'ajax',
      name: 'AFC Ajax',
      shortName: 'Ajax',
      emoji: '🔴⚪',
      stadium: 'Johan Cruyff Arena',
      manager: 'Francesco Farioli',
      budget: 80000000,
      players: [
        { id: 'gorter', name: 'Jay Gorter', position: 'GK', nationality: 'Netherlands', age: 23, overall: 75, wage: 40000 },
        { id: 'rensch', name: 'Devyne Rensch', position: 'RB', nationality: 'Netherlands', age: 21, overall: 76, wage: 50000 },
        { id: 'sutalo', name: 'Josip Šutalo', position: 'CB', nationality: 'Croatia', age: 23, overall: 76, wage: 50000 },
        { id: 'medic', name: 'Ahmetcan Kaplan', position: 'CB', nationality: 'Turkey', age: 22, overall: 74, wage: 40000 },
        { id: 'dijkstra', name: 'Owen Wijndal', position: 'LB', nationality: 'Netherlands', age: 24, overall: 75, wage: 50000 },
        { id: 'henderson_j', name: 'Jordan Henderson', position: 'CM', nationality: 'England', age: 34, overall: 78, wage: 150000 },
        { id: 'berghuis', name: 'Steven Berghuis', position: 'CM', nationality: 'Netherlands', age: 32, overall: 79, wage: 100000 },
        { id: 'taylor_k', name: 'Kenneth Taylor', position: 'CM', nationality: 'Netherlands', age: 22, overall: 76, wage: 50000 },
        { id: 'bergwijn', name: 'Steven Bergwijn', position: 'RW', nationality: 'Netherlands', age: 26, overall: 79, wage: 100000 },
        { id: 'brobbey', name: 'Brian Brobbey', position: 'ST', nationality: 'Netherlands', age: 22, overall: 77, wage: 80000 },
        { id: 'akpom', name: 'Chuba Akpom', position: 'ST', nationality: 'England', age: 29, overall: 76, wage: 80000 },
        { id: 'forbs', name: 'Carlos Forbs', position: 'LW', nationality: 'Portugal', age: 20, overall: 73, wage: 30000 },
        { id: 'fitz_jim', name: 'Silvano Vos', position: 'CM', nationality: 'Netherlands', age: 19, overall: 72, wage: 20000 },
        { id: 'gaaei', name: 'Anton Gaaei', position: 'RB', nationality: 'Denmark', age: 21, overall: 73, wage: 30000 },
        { id: 'baas', name: 'Gaetano Oristanio', position: 'CAM', nationality: 'Italy', age: 22, overall: 74, wage: 40000 },
        { id: 'traoré_h', name: 'Diant Ramaj', position: 'GK', nationality: 'Germany', age: 23, overall: 73, wage: 30000 },
        { id: 'klaasen', name: 'Davy Klaassen', position: 'CM', nationality: 'Netherlands', age: 31, overall: 76, wage: 80000 },
        { id: 'babadi', name: 'Benjamin Tahirović', position: 'CM', nationality: 'Sweden', age: 21, overall: 73, wage: 30000 },
        { id: 'haller', name: 'Sébastien Haller', position: 'ST', nationality: 'Ivory Coast', age: 30, overall: 77, wage: 100000 },
        { id: 'kudus', name: 'Mohammed Kudus', position: 'RW', nationality: 'Ghana', age: 23, overall: 79, wage: 80000 },
        { id: 'blind', name: 'Daley Blind', position: 'CB', nationality: 'Netherlands', age: 34, overall: 76, wage: 100000 },
      ]
    },
    {
      id: 'psv',
      name: 'PSV Eindhoven',
      shortName: 'PSV',
      emoji: '🔴⚪',
      stadium: 'Philips Stadion',
      manager: 'Peter Bosz',
      budget: 70000000,
      players: [
        { id: 'benitez_w', name: 'Walter Benítez', position: 'GK', nationality: 'Argentina', age: 32, overall: 80, wage: 80000 },
        { id: 'karsdorp', name: 'Rick Karsdorp', position: 'RB', nationality: 'Netherlands', age: 29, overall: 76, wage: 70000 },
        { id: 'obispo', name: 'Olivier Boscagli', position: 'CB', nationality: 'France', age: 27, overall: 77, wage: 70000 },
        { id: 'ramalho', name: 'André Ramalho', position: 'CB', nationality: 'Brazil', age: 31, overall: 76, wage: 60000 },
        { id: 'max_p', name: 'Phillipp Mwene', position: 'LB', nationality: 'Austria', age: 29, overall: 74, wage: 50000 },
        { id: 'schouten', name: 'Jerdy Schouten', position: 'CM', nationality: 'Netherlands', age: 27, overall: 79, wage: 80000 },
        { id: 'tillman', name: 'Malik Tillman', position: 'CM', nationality: 'USA', age: 22, overall: 76, wage: 60000 },
        { id: 'veerman', name: 'Joey Veerman', position: 'CM', nationality: 'Netherlands', age: 25, overall: 79, wage: 80000 },
        { id: 'bakayoko', name: 'Anwar El Ghazi', position: 'RW', nationality: 'Netherlands', age: 29, overall: 76, wage: 80000 },
        { id: 'pepi_r', name: 'Ricardo Pepi', position: 'ST', nationality: 'USA', age: 21, overall: 75, wage: 50000 },
        { id: 'saibari', name: 'Ismael Saibari', position: 'LW', nationality: 'Morocco', age: 23, overall: 76, wage: 60000 },
        { id: 'bakayoko_h', name: 'Yorbe Vertessen', position: 'ST', nationality: 'Belgium', age: 24, overall: 74, wage: 50000 },
        { id: 'sangare', name: 'Ibrahim Sangaré', position: 'CM', nationality: 'Ivory Coast', age: 26, overall: 81, wage: 100000 },
        { id: 'lozano', name: 'Hirving Lozano', position: 'RW', nationality: 'Mexico', age: 29, overall: 79, wage: 100000 },
        { id: 'dest', name: 'Sergiño Dest', position: 'RB', nationality: 'USA', age: 23, overall: 76, wage: 60000 },
        { id: 'teze', name: 'Jordan Teze', position: 'CB', nationality: 'Netherlands', age: 24, overall: 76, wage: 50000 },
        { id: 'gutierrez_h', name: 'Héctor Gómez', position: 'LB', nationality: 'Venezuela', age: 22, overall: 72, wage: 30000 },
        { id: 'luuk_de_j', name: 'Luuk de Jong', position: 'ST', nationality: 'Netherlands', age: 34, overall: 77, wage: 100000 },
        { id: 'de_jong_xavi', name: 'Xavi Simons', position: 'CAM', nationality: 'Netherlands', age: 21, overall: 82, wage: 100000 },
        { id: 'doan', name: 'Ritsu Doan', position: 'RW', nationality: 'Japan', age: 26, overall: 78, wage: 80000 },
        { id: 'flekken', name: 'Joris Kramer', position: 'GK', nationality: 'Netherlands', age: 24, overall: 72, wage: 30000 },
      ]
    },
  ]
};

// Primeira Liga (Portugal)
const primeiraLiga = {
  id: 'primeira_liga',
  name: 'Primeira Liga',
  country: 'Portugal',
  emoji: '🇵🇹',
  teams: [
    {
      id: 'benfica',
      name: 'SL Benfica',
      shortName: 'Benfica',
      emoji: '🔴',
      stadium: 'Estádio da Luz',
      manager: 'Roger Schmidt',
      budget: 90000000,
      players: [
        { id: 'trubin', name: 'Anatoliy Trubin', position: 'GK', nationality: 'Ukraine', age: 22, overall: 80, wage: 80000 },
        { id: 'bah', name: 'Alexander Bah', position: 'RB', nationality: 'Denmark', age: 25, overall: 76, wage: 60000 },
        { id: 'antonio_s', name: 'António Silva', position: 'CB', nationality: 'Portugal', age: 20, overall: 79, wage: 50000 },
        { id: 'otamendi', name: 'Nicolás Otamendi', position: 'CB', nationality: 'Argentina', age: 36, overall: 79, wage: 150000 },
        { id: 'grimaldo', name: 'Alejandro Grimaldo', position: 'LB', nationality: 'Spain', age: 28, overall: 82, wage: 100000 },
        { id: 'florentino', name: 'Florentino Luís', position: 'CM', nationality: 'Portugal', age: 24, overall: 78, wage: 80000 },
        { id: 'neres', name: 'David Neres', position: 'RW', nationality: 'Brazil', age: 27, overall: 79, wage: 100000 },
        { id: 'aursnes', name: 'Fredrik Aursnes', position: 'CM', nationality: 'Norway', age: 28, overall: 78, wage: 70000 },
        { id: 'rafa_s', name: 'Rafa Silva', position: 'LW', nationality: 'Portugal', age: 31, overall: 78, wage: 100000 },
        { id: 'goncalves_g', name: 'Gonçalo Ramos', position: 'ST', nationality: 'Portugal', age: 22, overall: 81, wage: 80000 },
        { id: 'akturkoglu', name: 'Orkun Kökçü', position: 'CAM', nationality: 'Turkey', age: 23, overall: 78, wage: 80000 },
        { id: 'musa_a', name: 'Arthur Cabral', position: 'ST', nationality: 'Brazil', age: 26, overall: 77, wage: 80000 },
        { id: 'joao_mario', name: 'João Mário', position: 'CM', nationality: 'Portugal', age: 31, overall: 77, wage: 100000 },
        { id: 'jurásek', name: 'Matěj Jurásek', position: 'LB', nationality: 'Czech Republic', age: 21, overall: 73, wage: 30000 },
        { id: 'chiquinho', name: 'Chiquinho', position: 'RW', nationality: 'Portugal', age: 25, overall: 74, wage: 50000 },
        { id: 'diogo_g', name: 'Diogo Gonçalves', position: 'RW', nationality: 'Portugal', age: 27, overall: 74, wage: 60000 },
        { id: 'draxler', name: 'Julian Draxler', position: 'LW', nationality: 'Germany', age: 30, overall: 76, wage: 100000 },
        { id: 'barreiro', name: 'Marcos Leonardo', position: 'ST', nationality: 'Brazil', age: 22, overall: 76, wage: 70000 },
        { id: 'morato', name: 'Morato', position: 'CB', nationality: 'Brazil', age: 23, overall: 75, wage: 50000 },
        { id: 'vlachodimos', name: 'Odysseas Vlachodimos', position: 'GK', nationality: 'Greece', age: 29, overall: 78, wage: 80000 },
        { id: 'taarabt', name: 'Adel Taarabt', position: 'CAM', nationality: 'Morocco', age: 35, overall: 74, wage: 80000 },
      ]
    },
    {
      id: 'porto',
      name: 'FC Porto',
      shortName: 'Porto',
      emoji: '🔵⚪',
      stadium: 'Estádio do Dragão',
      manager: 'Sérgio Conceição',
      budget: 80000000,
      players: [
        { id: 'costa_dg', name: 'Diogo Costa', position: 'GK', nationality: 'Portugal', age: 24, overall: 83, wage: 100000 },
        { id: 'joao_mario_p', name: 'João Mário', position: 'RB', nationality: 'Portugal', age: 24, overall: 77, wage: 60000 },
        { id: 'mbemba', name: 'Chancel Mbemba', position: 'CB', nationality: 'DR Congo', age: 30, overall: 78, wage: 100000 },
        { id: 'cardoso', name: 'Pepe', position: 'CB', nationality: 'Portugal', age: 41, overall: 75, wage: 150000 },
        { id: 'sanusi', name: 'Zaidu Sanusi', position: 'LB', nationality: 'Nigeria', age: 27, overall: 76, wage: 60000 },
        { id: 'grujic', name: 'Marko Grujić', position: 'CM', nationality: 'Serbia', age: 28, overall: 77, wage: 70000 },
        { id: 'eustaquio', name: 'Stephen Eustáquio', position: 'CM', nationality: 'Canada', age: 27, overall: 78, wage: 80000 },
        { id: 'gonzalez_o', name: 'Pepê', position: 'RW', nationality: 'Brazil', age: 26, overall: 78, wage: 80000 },
        { id: 'galeno', name: 'Galeno', position: 'LW', nationality: 'Brazil', age: 26, overall: 79, wage: 100000 },
        { id: 'evanilson', name: 'Evanilson', position: 'ST', nationality: 'Brazil', age: 24, overall: 79, wage: 100000 },
        { id: 'taremi', name: 'Mehdi Taremi', position: 'ST', nationality: 'Iran', age: 32, overall: 82, wage: 150000 },
        { id: 'conceicao', name: 'Francisco Conceição', position: 'RW', nationality: 'Portugal', age: 21, overall: 76, wage: 50000 },
        { id: 'silva_t', name: 'Toni Martínez', position: 'ST', nationality: 'Spain', age: 27, overall: 74, wage: 50000 },
        { id: 'veron', name: 'Danny Namaso', position: 'RW', nationality: 'England', age: 23, overall: 73, wage: 40000 },
        { id: 'zé_pedro', name: 'Zé Pedro', position: 'CB', nationality: 'Portugal', age: 23, overall: 74, wage: 40000 },
        { id: 'martim_f', name: 'Martim Fernandes', position: 'RB', nationality: 'Portugal', age: 19, overall: 70, wage: 15000 },
        { id: 'vana_p', name: 'Iván Jaime', position: 'CM', nationality: 'Spain', age: 22, overall: 73, wage: 30000 },
        { id: 'otavio', name: 'Otávio', position: 'CM', nationality: 'Portugal', age: 29, overall: 78, wage: 100000 },
        { id: 'rodrigues_c', name: 'Wendell', position: 'LB', nationality: 'Brazil', age: 31, overall: 76, wage: 80000 },
        { id: 'nico_g', name: 'Nico González', position: 'CM', nationality: 'Spain', age: 22, overall: 76, wage: 50000 },
        { id: 'diogo_c_res', name: 'Samuel Portugal', position: 'GK', nationality: 'Portugal', age: 30, overall: 73, wage: 40000 },
      ]
    },
  ]
};

module.exports = { ligue1, eredivisie, primeiraLiga };
