// La Liga - Real Madrid & Barcelona (main teams)
const laLiga = {
  id: 'la_liga',
  name: 'La Liga',
  country: 'Spain',
  emoji: '🇪🇸',
  teams: [
    {
      id: 'real_madrid',
      name: 'Real Madrid',
      shortName: 'Real Madrid',
      emoji: '⚪',
      stadium: 'Santiago Bernabéu',
      manager: 'Carlo Ancelotti',
      budget: 300000000,
      players: [
        { id: 'courtois', name: 'Thibaut Courtois', position: 'GK', nationality: 'Belgium', age: 32, overall: 90, wage: 300000 },
        { id: 'carvajal', name: 'Dani Carvajal', position: 'RB', nationality: 'Spain', age: 32, overall: 84, wage: 200000 },
        { id: 'militao', name: 'Éder Militão', position: 'CB', nationality: 'Brazil', age: 26, overall: 86, wage: 200000 },
        { id: 'alaba', name: 'David Alaba', position: 'CB', nationality: 'Austria', age: 32, overall: 83, wage: 250000 },
        { id: 'mendy_f', name: 'Ferland Mendy', position: 'LB', nationality: 'France', age: 29, overall: 83, wage: 180000 },
        { id: 'tchouameni', name: 'Aurélien Tchouaméni', position: 'CM', nationality: 'France', age: 24, overall: 85, wage: 200000 },
        { id: 'valverde', name: 'Federico Valverde', position: 'CM', nationality: 'Uruguay', age: 26, overall: 86, wage: 200000 },
        { id: 'bellingham', name: 'Jude Bellingham', position: 'CAM', nationality: 'England', age: 21, overall: 89, wage: 350000 },
        { id: 'vinicius', name: 'Vinícius Júnior', position: 'LW', nationality: 'Brazil', age: 24, overall: 91, wage: 400000 },
        { id: 'mbappe', name: 'Kylian Mbappé', position: 'ST', nationality: 'France', age: 26, overall: 93, wage: 1000000 },
        { id: 'rodrygo', name: 'Rodrygo', position: 'RW', nationality: 'Brazil', age: 23, overall: 85, wage: 200000 },
        { id: 'modric', name: 'Luka Modrić', position: 'CM', nationality: 'Croatia', age: 39, overall: 82, wage: 300000 },
        { id: 'kroos', name: 'Toni Kroos', position: 'CM', nationality: 'Germany', age: 34, overall: 85, wage: 350000 },
        { id: 'camavinga', name: 'Eduardo Camavinga', position: 'CM', nationality: 'France', age: 21, overall: 83, wage: 150000 },
        { id: 'rudiger', name: 'Antonio Rüdiger', position: 'CB', nationality: 'Germany', age: 31, overall: 83, wage: 200000 },
        { id: 'nacho', name: 'Nacho Fernández', position: 'CB', nationality: 'Spain', age: 34, overall: 78, wage: 150000 },
        { id: 'vazquez_l', name: 'Lucas Vázquez', position: 'RB', nationality: 'Spain', age: 33, overall: 77, wage: 130000 },
        { id: 'joselu', name: 'Joselu', position: 'ST', nationality: 'Spain', age: 34, overall: 77, wage: 100000 },
        { id: 'diaz_brahim', name: 'Brahim Díaz', position: 'CAM', nationality: 'Spain', age: 25, overall: 79, wage: 100000 },
        { id: 'guler', name: 'Arda Güler', position: 'CAM', nationality: 'Turkey', age: 19, overall: 77, wage: 80000 },
        { id: 'lunin', name: 'Andriy Lunin', position: 'GK', nationality: 'Ukraine', age: 25, overall: 79, wage: 80000 },
      ]
    },
    {
      id: 'barcelona',
      name: 'FC Barcelona',
      shortName: 'Barcelona',
      emoji: '🔴🔵',
      stadium: 'Spotify Camp Nou',
      manager: 'Hansi Flick',
      budget: 200000000,
      players: [
        { id: 'ter_stegen', name: 'Marc-André ter Stegen', position: 'GK', nationality: 'Germany', age: 32, overall: 87, wage: 250000 },
        { id: 'kounde', name: 'Jules Koundé', position: 'RB', nationality: 'France', age: 25, overall: 85, wage: 180000 },
        { id: 'araujo', name: 'Ronald Araújo', position: 'CB', nationality: 'Uruguay', age: 25, overall: 86, wage: 180000 },
        { id: 'martinez_i', name: 'Íñigo Martínez', position: 'CB', nationality: 'Spain', age: 33, overall: 80, wage: 150000 },
        { id: 'balde', name: 'Alejandro Balde', position: 'LB', nationality: 'Spain', age: 20, overall: 81, wage: 100000 },
        { id: 'pedri', name: 'Pedri', position: 'CM', nationality: 'Spain', age: 22, overall: 87, wage: 200000 },
        { id: 'gavi', name: 'Gavi', position: 'CM', nationality: 'Spain', age: 20, overall: 85, wage: 180000 },
        { id: 'de_jong', name: 'Frenkie de Jong', position: 'CM', nationality: 'Netherlands', age: 27, overall: 85, wage: 200000 },
        { id: 'yamal', name: 'Lamine Yamal', position: 'RW', nationality: 'Spain', age: 17, overall: 84, wage: 100000 },
        { id: 'lewandowski', name: 'Robert Lewandowski', position: 'ST', nationality: 'Poland', age: 36, overall: 87, wage: 400000 },
        { id: 'raphinha', name: 'Raphinha', position: 'LW', nationality: 'Brazil', age: 27, overall: 83, wage: 200000 },
        { id: 'ferran_t', name: 'Ferran Torres', position: 'RW', nationality: 'Spain', age: 24, overall: 79, wage: 150000 },
        { id: 'olmo', name: 'Dani Olmo', position: 'CAM', nationality: 'Spain', age: 26, overall: 83, wage: 200000 },
        { id: 'cancelo', name: 'João Cancelo', position: 'RB', nationality: 'Portugal', age: 30, overall: 82, wage: 200000 },
        { id: 'christensen', name: 'Andreas Christensen', position: 'CB', nationality: 'Denmark', age: 28, overall: 81, wage: 150000 },
        { id: 'cubarsí', name: 'Pau Cubarsí', position: 'CB', nationality: 'Spain', age: 17, overall: 78, wage: 30000 },
        { id: 'casado', name: 'Marc Casadó', position: 'CM', nationality: 'Spain', age: 21, overall: 75, wage: 40000 },
        { id: 'vitor_r', name: 'Vitor Roque', position: 'ST', nationality: 'Brazil', age: 19, overall: 74, wage: 50000 },
        { id: 'felixj', name: 'João Félix', position: 'CAM', nationality: 'Portugal', age: 25, overall: 82, wage: 200000 },
        { id: 'inaki_p', name: 'Iñaki Peña', position: 'GK', nationality: 'Spain', age: 25, overall: 75, wage: 50000 },
        { id: 'fort', name: 'Gerard Martín', position: 'LB', nationality: 'Spain', age: 22, overall: 73, wage: 30000 },
      ]
    },
    {
      id: 'atletico',
      name: 'Atlético de Madrid',
      shortName: 'Atlético',
      emoji: '🔴⚪',
      stadium: 'Cívitas Metropolitano',
      manager: 'Diego Simeone',
      budget: 120000000,
      players: [
        { id: 'oblak', name: 'Jan Oblak', position: 'GK', nationality: 'Slovenia', age: 31, overall: 88, wage: 250000 },
        { id: 'molina', name: 'Nahuel Molina', position: 'RB', nationality: 'Argentina', age: 26, overall: 80, wage: 100000 },
        { id: 'gimenez', name: 'José María Giménez', position: 'CB', nationality: 'Uruguay', age: 29, overall: 82, wage: 150000 },
        { id: 'witsel', name: 'Axel Witsel', position: 'CB', nationality: 'Belgium', age: 35, overall: 78, wage: 130000 },
        { id: 'riquelme', name: 'Reinildo', position: 'LB', nationality: 'Mozambique', age: 30, overall: 78, wage: 100000 },
        { id: 'koke', name: 'Koke', position: 'CM', nationality: 'Spain', age: 32, overall: 81, wage: 200000 },
        { id: 'llorente', name: 'Marcos Llorente', position: 'CM', nationality: 'Spain', age: 29, overall: 81, wage: 150000 },
        { id: 'barrios', name: 'Pablo Barrios', position: 'CM', nationality: 'Spain', age: 21, overall: 77, wage: 50000 },
        { id: 'griezmann', name: 'Antoine Griezmann', position: 'ST', nationality: 'France', age: 33, overall: 86, wage: 300000 },
        { id: 'morata', name: 'Álvaro Morata', position: 'ST', nationality: 'Spain', age: 32, overall: 81, wage: 180000 },
        { id: 'correa_a', name: 'Ángel Correa', position: 'ST', nationality: 'Argentina', age: 29, overall: 79, wage: 150000 },
        { id: 'depay', name: 'Memphis Depay', position: 'LW', nationality: 'Netherlands', age: 30, overall: 79, wage: 150000 },
        { id: 'samuel_l', name: 'Samuel Lino', position: 'LW', nationality: 'Brazil', age: 25, overall: 77, wage: 70000 },
        { id: 'musso', name: 'Juan Musso', position: 'GK', nationality: 'Argentina', age: 30, overall: 81, wage: 120000 },
        { id: 'savic', name: 'Stefan Savić', position: 'CB', nationality: 'Montenegro', age: 33, overall: 78, wage: 130000 },
        { id: 'hermoso', name: 'Mario Hermoso', position: 'CB', nationality: 'Spain', age: 29, overall: 79, wage: 100000 },
        { id: 'gallagher_c', name: 'Conor Gallagher', position: 'CM', nationality: 'England', age: 24, overall: 78, wage: 150000 },
        { id: 'riquelme_r', name: 'Rodrigo Riquelme', position: 'LW', nationality: 'Spain', age: 23, overall: 75, wage: 50000 },
        { id: 'simeone_g', name: 'Giovanni Simeone', position: 'ST', nationality: 'Argentina', age: 29, overall: 78, wage: 80000 },
        { id: 'lenglet', name: 'Clément Lenglet', position: 'CB', nationality: 'France', age: 29, overall: 77, wage: 120000 },
        { id: 'lemar', name: 'Thomas Lemar', position: 'LW', nationality: 'France', age: 29, overall: 78, wage: 100000 },
      ]
    },
  ]
};

// Bundesliga
const bundesliga = {
  id: 'bundesliga',
  name: 'Bundesliga',
  country: 'Germany',
  emoji: '🇩🇪',
  teams: [
    {
      id: 'bayern',
      name: 'Bayern München',
      shortName: 'Bayern',
      emoji: '🔴',
      stadium: 'Allianz Arena',
      manager: 'Vincent Kompany',
      budget: 200000000,
      players: [
        { id: 'neuer', name: 'Manuel Neuer', position: 'GK', nationality: 'Germany', age: 38, overall: 84, wage: 300000 },
        { id: 'kimmich', name: 'Joshua Kimmich', position: 'RB', nationality: 'Germany', age: 29, overall: 88, wage: 300000 },
        { id: 'de_ligt', name: 'Matthijs de Ligt', position: 'CB', nationality: 'Netherlands', age: 25, overall: 83, wage: 200000 },
        { id: 'upamecano', name: 'Dayot Upamecano', position: 'CB', nationality: 'France', age: 25, overall: 83, wage: 180000 },
        { id: 'davies_a', name: 'Alphonso Davies', position: 'LB', nationality: 'Canada', age: 23, overall: 85, wage: 200000 },
        { id: 'laimer', name: 'Konrad Laimer', position: 'CM', nationality: 'Austria', age: 27, overall: 80, wage: 150000 },
        { id: 'goretzka', name: 'Leon Goretzka', position: 'CM', nationality: 'Germany', age: 29, overall: 83, wage: 250000 },
        { id: 'muller', name: 'Thomas Müller', position: 'CAM', nationality: 'Germany', age: 35, overall: 82, wage: 300000 },
        { id: 'coman', name: 'Kingsley Coman', position: 'RW', nationality: 'France', age: 28, overall: 83, wage: 200000 },
        { id: 'kane', name: 'Harry Kane', position: 'ST', nationality: 'England', age: 31, overall: 90, wage: 400000 },
        { id: 'gnabry', name: 'Serge Gnabry', position: 'LW', nationality: 'Germany', age: 29, overall: 81, wage: 200000 },
        { id: 'sane', name: 'Leroy Sané', position: 'RW', nationality: 'Germany', age: 28, overall: 84, wage: 250000 },
        { id: 'musiala', name: 'Jamal Musiala', position: 'CAM', nationality: 'Germany', age: 21, overall: 87, wage: 200000 },
        { id: 'pavlovic', name: 'Aleksandar Pavlović', position: 'CM', nationality: 'Germany', age: 20, overall: 77, wage: 50000 },
        { id: 'peretz', name: 'Daniel Peretz', position: 'GK', nationality: 'Israel', age: 24, overall: 74, wage: 40000 },
        { id: 'kim_m', name: 'Kim Min-Jae', position: 'CB', nationality: 'South Korea', age: 28, overall: 84, wage: 200000 },
        { id: 'mazraoui', name: 'Noussair Mazraoui', position: 'RB', nationality: 'Morocco', age: 26, overall: 81, wage: 150000 },
        { id: 'guerreiro', name: 'Raphaël Guerreiro', position: 'LB', nationality: 'Portugal', age: 30, overall: 81, wage: 150000 },
        { id: 'olise', name: 'Michael Olise', position: 'RW', nationality: 'France', age: 22, overall: 82, wage: 180000 },
        { id: 'palhinha', name: 'João Palhinha', position: 'CM', nationality: 'Portugal', age: 28, overall: 82, wage: 150000 },
        { id: 'tel', name: 'Mathys Tel', position: 'ST', nationality: 'France', age: 19, overall: 77, wage: 80000 },
      ]
    },
    {
      id: 'dortmund',
      name: 'Borussia Dortmund',
      shortName: 'Dortmund',
      emoji: '🟡',
      stadium: 'Signal Iduna Park',
      manager: 'Niko Kovač',
      budget: 120000000,
      players: [
        { id: 'kobel', name: 'Gregor Kobel', position: 'GK', nationality: 'Switzerland', age: 26, overall: 84, wage: 100000 },
        { id: 'ryerson', name: 'Julian Ryerson', position: 'RB', nationality: 'Norway', age: 27, overall: 76, wage: 60000 },
        { id: 'hummels', name: 'Mats Hummels', position: 'CB', nationality: 'Germany', age: 35, overall: 81, wage: 200000 },
        { id: 'schlotterbeck', name: 'Nico Schlotterbeck', position: 'CB', nationality: 'Germany', age: 24, overall: 81, wage: 100000 },
        { id: 'maatsen', name: 'Ian Maatsen', position: 'LB', nationality: 'Netherlands', age: 22, overall: 78, wage: 70000 },
        { id: 'can', name: 'Emre Can', position: 'CM', nationality: 'Germany', age: 30, overall: 79, wage: 150000 },
        { id: 'sabitzer', name: 'Marcel Sabitzer', position: 'CM', nationality: 'Austria', age: 30, overall: 79, wage: 120000 },
        { id: 'brandt', name: 'Julian Brandt', position: 'CAM', nationality: 'Germany', age: 28, overall: 81, wage: 130000 },
        { id: 'adeyemi', name: 'Karim Adeyemi', position: 'LW', nationality: 'Germany', age: 22, overall: 79, wage: 80000 },
        { id: 'fullkrug', name: 'Niclas Füllkrug', position: 'ST', nationality: 'Germany', age: 31, overall: 80, wage: 120000 },
        { id: 'sancho_j', name: 'Jadon Sancho', position: 'RW', nationality: 'England', age: 24, overall: 81, wage: 150000 },
        { id: 'reus', name: 'Marco Reus', position: 'CAM', nationality: 'Germany', age: 35, overall: 79, wage: 200000 },
        { id: 'gittens', name: 'Jamie Gittens', position: 'LW', nationality: 'England', age: 20, overall: 76, wage: 40000 },
        { id: 'nmecha', name: 'Felix Nmecha', position: 'CM', nationality: 'Germany', age: 23, overall: 77, wage: 70000 },
        { id: 'bensebaini', name: 'Ramy Bensebaïni', position: 'LB', nationality: 'Algeria', age: 29, overall: 78, wage: 80000 },
        { id: 'sule', name: 'Niklas Süle', position: 'CB', nationality: 'Germany', age: 29, overall: 79, wage: 150000 },
        { id: 'morey', name: 'Mateu Morey', position: 'RB', nationality: 'Spain', age: 24, overall: 73, wage: 40000 },
        { id: 'duranville', name: 'Julien Duranville', position: 'RW', nationality: 'Belgium', age: 18, overall: 74, wage: 25000 },
        { id: 'malen', name: 'Donyell Malen', position: 'RW', nationality: 'Netherlands', age: 25, overall: 79, wage: 100000 },
        { id: 'lotka', name: 'Alexander Meyer', position: 'GK', nationality: 'Germany', age: 31, overall: 73, wage: 40000 },
        { id: 'beier', name: 'Maximilian Beier', position: 'ST', nationality: 'Germany', age: 21, overall: 77, wage: 60000 },
      ]
    },
  ]
};

// Serie A
const serieA = {
  id: 'serie_a',
  name: 'Serie A',
  country: 'Italy',
  emoji: '🇮🇹',
  teams: [
    {
      id: 'inter',
      name: 'Inter Milan',
      shortName: 'Inter',
      emoji: '🔵⚫',
      stadium: 'Giuseppe Meazza',
      manager: 'Simone Inzaghi',
      budget: 150000000,
      players: [
        { id: 'sommer', name: 'Yann Sommer', position: 'GK', nationality: 'Switzerland', age: 35, overall: 85, wage: 150000 },
        { id: 'darmian', name: 'Matteo Darmian', position: 'RB', nationality: 'Italy', age: 34, overall: 77, wage: 100000 },
        { id: 'acerbi', name: 'Francesco Acerbi', position: 'CB', nationality: 'Italy', age: 36, overall: 80, wage: 120000 },
        { id: 'bastoni', name: 'Alessandro Bastoni', position: 'CB', nationality: 'Italy', age: 25, overall: 86, wage: 200000 },
        { id: 'dimarco', name: 'Federico Dimarco', position: 'LB', nationality: 'Italy', age: 26, overall: 84, wage: 150000 },
        { id: 'barella', name: 'Nicolò Barella', position: 'CM', nationality: 'Italy', age: 27, overall: 87, wage: 200000 },
        { id: 'calhanoglu', name: 'Hakan Çalhanoğlu', position: 'CM', nationality: 'Turkey', age: 30, overall: 84, wage: 150000 },
        { id: 'mkhitaryan', name: 'Henrikh Mkhitaryan', position: 'CM', nationality: 'Armenia', age: 35, overall: 79, wage: 150000 },
        { id: 'darmian_2', name: 'Denzel Dumfries', position: 'RW', nationality: 'Netherlands', age: 28, overall: 82, wage: 120000 },
        { id: 'lautaro', name: 'Lautaro Martínez', position: 'ST', nationality: 'Argentina', age: 27, overall: 88, wage: 300000 },
        { id: 'thuram_m', name: 'Marcus Thuram', position: 'ST', nationality: 'France', age: 27, overall: 84, wage: 200000 },
        { id: 'sanchez_a', name: 'Alexis Sánchez', position: 'LW', nationality: 'Chile', age: 35, overall: 76, wage: 200000 },
        { id: 'frattesi', name: 'Davide Frattesi', position: 'CM', nationality: 'Italy', age: 24, overall: 80, wage: 100000 },
        { id: 'de_vrij', name: 'Stefan de Vrij', position: 'CB', nationality: 'Netherlands', age: 32, overall: 82, wage: 150000 },
        { id: 'pavard', name: 'Benjamin Pavard', position: 'CB', nationality: 'France', age: 28, overall: 82, wage: 150000 },
        { id: 'carlos_a', name: 'Carlos Augusto', position: 'LB', nationality: 'Brazil', age: 25, overall: 78, wage: 70000 },
        { id: 'bisseck', name: 'Yann Bisseck', position: 'CB', nationality: 'Germany', age: 23, overall: 75, wage: 40000 },
        { id: 'arnautovic', name: 'Marko Arnautović', position: 'ST', nationality: 'Austria', age: 35, overall: 76, wage: 120000 },
        { id: 'martinez_l', name: 'Joaquín Correa', position: 'LW', nationality: 'Argentina', age: 30, overall: 75, wage: 100000 },
        { id: 'audero', name: 'Emil Audero', position: 'GK', nationality: 'Italy', age: 27, overall: 76, wage: 50000 },
        { id: 'sensi', name: 'Stefano Sensi', position: 'CM', nationality: 'Italy', age: 29, overall: 74, wage: 70000 },
      ]
    },
    {
      id: 'juventus',
      name: 'Juventus',
      shortName: 'Juventus',
      emoji: '⚫⚪',
      stadium: 'Allianz Stadium',
      manager: 'Thiago Motta',
      budget: 130000000,
      players: [
        { id: 'szczesny', name: 'Wojciech Szczęsny', position: 'GK', nationality: 'Poland', age: 34, overall: 84, wage: 200000 },
        { id: 'cambiaso', name: 'Andrea Cambiaso', position: 'RB', nationality: 'Italy', age: 24, overall: 80, wage: 100000 },
        { id: 'bremer', name: 'Gleison Bremer', position: 'CB', nationality: 'Brazil', age: 27, overall: 84, wage: 150000 },
        { id: 'gatti', name: 'Federico Gatti', position: 'CB', nationality: 'Italy', age: 26, overall: 76, wage: 60000 },
        { id: 'danilo', name: 'Danilo', position: 'LB', nationality: 'Brazil', age: 33, overall: 78, wage: 150000 },
        { id: 'locatelli', name: 'Manuel Locatelli', position: 'CM', nationality: 'Italy', age: 26, overall: 80, wage: 130000 },
        { id: 'rabiot', name: 'Adrien Rabiot', position: 'CM', nationality: 'France', age: 29, overall: 81, wage: 200000 },
        { id: 'mckennie', name: 'Weston McKennie', position: 'CM', nationality: 'USA', age: 26, overall: 77, wage: 100000 },
        { id: 'chiesa_f', name: 'Federico Chiesa', position: 'RW', nationality: 'Italy', age: 27, overall: 82, wage: 150000 },
        { id: 'vlahovic', name: 'Dušan Vlahović', position: 'ST', nationality: 'Serbia', age: 24, overall: 85, wage: 300000 },
        { id: 'kostic', name: 'Filip Kostić', position: 'LW', nationality: 'Serbia', age: 31, overall: 79, wage: 100000 },
        { id: 'milik', name: 'Arkadiusz Milik', position: 'ST', nationality: 'Poland', age: 30, overall: 78, wage: 150000 },
        { id: 'iling', name: 'Samuel Iling-Junior', position: 'LW', nationality: 'England', age: 20, overall: 74, wage: 30000 },
        { id: 'yildiz', name: 'Kenan Yıldız', position: 'CAM', nationality: 'Turkey', age: 19, overall: 77, wage: 40000 },
        { id: 'fagioli', name: 'Nicolò Fagioli', position: 'CM', nationality: 'Italy', age: 23, overall: 76, wage: 50000 },
        { id: 'alex_s', name: 'Alex Sandro', position: 'LB', nationality: 'Brazil', age: 33, overall: 75, wage: 120000 },
        { id: 'rugani', name: 'Daniele Rugani', position: 'CB', nationality: 'Italy', age: 30, overall: 76, wage: 100000 },
        { id: 'perin', name: 'Mattia Perin', position: 'GK', nationality: 'Italy', age: 31, overall: 77, wage: 80000 },
        { id: 'nonge', name: 'Joseph Nonge', position: 'CM', nationality: 'Belgium', age: 18, overall: 68, wage: 10000 },
        { id: 'weah', name: 'Timothy Weah', position: 'RW', nationality: 'USA', age: 24, overall: 74, wage: 60000 },
        { id: 'kean', name: 'Moise Kean', position: 'ST', nationality: 'Italy', age: 24, overall: 78, wage: 80000 },
      ]
    },
  ]
};

module.exports = { laLiga, bundesliga, serieA };
