// Premier League - Top 6 teams with real squads (2024-25 season)
const premierLeague = {
  id: 'premier_league',
  name: 'Premier League',
  country: 'England',
  emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  teams: [
    {
      id: 'man_city',
      name: 'Manchester City',
      shortName: 'Man City',
      emoji: '🔵',
      stadium: 'Etihad Stadium',
      manager: 'Pep Guardiola',
      budget: 200000000,
      players: [
        { id: 'ederson', name: 'Ederson', position: 'GK', nationality: 'Brazil', age: 31, overall: 89, wage: 180000 },
        { id: 'walker', name: 'Kyle Walker', position: 'RB', nationality: 'England', age: 34, overall: 83, wage: 120000 },
        { id: 'dias', name: 'Rúben Dias', position: 'CB', nationality: 'Portugal', age: 27, overall: 89, wage: 150000 },
        { id: 'akanji', name: 'Manuel Akanji', position: 'CB', nationality: 'Switzerland', age: 29, overall: 85, wage: 130000 },
        { id: 'gvardiol', name: 'Joško Gvardiol', position: 'LB', nationality: 'Croatia', age: 22, overall: 85, wage: 120000 },
        { id: 'rodri', name: 'Rodri', position: 'CM', nationality: 'Spain', age: 28, overall: 91, wage: 220000 },
        { id: 'de_bruyne', name: 'Kevin De Bruyne', position: 'CM', nationality: 'Belgium', age: 33, overall: 91, wage: 400000 },
        { id: 'bernardo', name: 'Bernardo Silva', position: 'CM', nationality: 'Portugal', age: 30, overall: 88, wage: 200000 },
        { id: 'doku', name: 'Jérémy Doku', position: 'LW', nationality: 'Belgium', age: 22, overall: 83, wage: 100000 },
        { id: 'haaland', name: 'Erling Haaland', position: 'ST', nationality: 'Norway', age: 24, overall: 94, wage: 450000 },
        { id: 'foden', name: 'Phil Foden', position: 'RW', nationality: 'England', age: 24, overall: 90, wage: 250000 },
        { id: 'ortega', name: 'Stefan Ortega', position: 'GK', nationality: 'Germany', age: 32, overall: 78, wage: 50000 },
        { id: 'kovacic', name: 'Mateo Kovačić', position: 'CM', nationality: 'Croatia', age: 30, overall: 83, wage: 130000 },
        { id: 'stones', name: 'John Stones', position: 'CB', nationality: 'England', age: 30, overall: 85, wage: 120000 },
        { id: 'silva_b', name: 'Savinho', position: 'RW', nationality: 'Brazil', age: 20, overall: 79, wage: 80000 },
        { id: 'grealish', name: 'Jack Grealish', position: 'LW', nationality: 'England', age: 29, overall: 83, wage: 230000 },
        { id: 'mcatee', name: 'James McAtee', position: 'CM', nationality: 'England', age: 22, overall: 74, wage: 30000 },
        { id: 'gomez_s', name: 'Sergio Gómez', position: 'LB', nationality: 'Spain', age: 24, overall: 74, wage: 35000 },
        { id: 'lewis_r', name: 'Rico Lewis', position: 'RB', nationality: 'England', age: 20, overall: 78, wage: 30000 },
        { id: 'bobb', name: 'Oscar Bobb', position: 'RW', nationality: 'Norway', age: 21, overall: 74, wage: 25000 },
        { id: 'nunes', name: 'Matheus Nunes', position: 'CM', nationality: 'Portugal', age: 26, overall: 79, wage: 90000 },
      ]
    },
    {
      id: 'arsenal',
      name: 'Arsenal',
      shortName: 'Arsenal',
      emoji: '🔴',
      stadium: 'Emirates Stadium',
      manager: 'Mikel Arteta',
      budget: 180000000,
      players: [
        { id: 'raya', name: 'David Raya', position: 'GK', nationality: 'Spain', age: 29, overall: 86, wage: 120000 },
        { id: 'white_b', name: 'Ben White', position: 'RB', nationality: 'England', age: 27, overall: 85, wage: 130000 },
        { id: 'saliba', name: 'William Saliba', position: 'CB', nationality: 'France', age: 23, overall: 87, wage: 150000 },
        { id: 'gabriel', name: 'Gabriel Magalhães', position: 'CB', nationality: 'Brazil', age: 26, overall: 86, wage: 140000 },
        { id: 'zinchenko', name: 'Oleksandr Zinchenko', position: 'LB', nationality: 'Ukraine', age: 27, overall: 81, wage: 100000 },
        { id: 'partey', name: 'Thomas Partey', position: 'CM', nationality: 'Ghana', age: 31, overall: 83, wage: 130000 },
        { id: 'rice', name: 'Declan Rice', position: 'CM', nationality: 'England', age: 25, overall: 87, wage: 300000 },
        { id: 'odegaard', name: 'Martin Ødegaard', position: 'CAM', nationality: 'Norway', age: 26, overall: 88, wage: 250000 },
        { id: 'saka', name: 'Bukayo Saka', position: 'RW', nationality: 'England', age: 23, overall: 88, wage: 250000 },
        { id: 'havertz', name: 'Kai Havertz', position: 'ST', nationality: 'Germany', age: 25, overall: 83, wage: 200000 },
        { id: 'trossard', name: 'Leandro Trossard', position: 'LW', nationality: 'Belgium', age: 29, overall: 82, wage: 120000 },
        { id: 'jesus', name: 'Gabriel Jesus', position: 'ST', nationality: 'Brazil', age: 27, overall: 82, wage: 150000 },
        { id: 'martinelli', name: 'Gabriel Martinelli', position: 'LW', nationality: 'Brazil', age: 23, overall: 84, wage: 180000 },
        { id: 'calafiori', name: 'Riccardo Calafiori', position: 'CB', nationality: 'Italy', age: 22, overall: 81, wage: 90000 },
        { id: 'merino', name: 'Mikel Merino', position: 'CM', nationality: 'Spain', age: 28, overall: 83, wage: 130000 },
        { id: 'jorginho', name: 'Jorginho', position: 'CM', nationality: 'Italy', age: 33, overall: 79, wage: 100000 },
        { id: 'timber', name: 'Jurriën Timber', position: 'RB', nationality: 'Netherlands', age: 23, overall: 82, wage: 100000 },
        { id: 'nketiah', name: 'Eddie Nketiah', position: 'ST', nationality: 'England', age: 25, overall: 75, wage: 70000 },
        { id: 'tomiyasu', name: 'Takehiro Tomiyasu', position: 'RB', nationality: 'Japan', age: 26, overall: 79, wage: 70000 },
        { id: 'lewis_sk', name: 'Emile Smith Rowe', position: 'CAM', nationality: 'England', age: 24, overall: 78, wage: 80000 },
        { id: 'ramsdale', name: 'Aaron Ramsdale', position: 'GK', nationality: 'England', age: 26, overall: 82, wage: 90000 },
      ]
    },
    {
      id: 'liverpool',
      name: 'Liverpool',
      shortName: 'Liverpool',
      emoji: '🔴',
      stadium: 'Anfield',
      manager: 'Arne Slot',
      budget: 160000000,
      players: [
        { id: 'alisson', name: 'Alisson Becker', position: 'GK', nationality: 'Brazil', age: 32, overall: 90, wage: 200000 },
        { id: 'alexander_arnold', name: 'Trent Alexander-Arnold', position: 'RB', nationality: 'England', age: 26, overall: 88, wage: 220000 },
        { id: 'van_dijk', name: 'Virgil van Dijk', position: 'CB', nationality: 'Netherlands', age: 33, overall: 88, wage: 200000 },
        { id: 'konate', name: 'Ibrahima Konaté', position: 'CB', nationality: 'France', age: 25, overall: 85, wage: 120000 },
        { id: 'robertson', name: 'Andrew Robertson', position: 'LB', nationality: 'Scotland', age: 30, overall: 85, wage: 150000 },
        { id: 'mac_allister', name: 'Alexis Mac Allister', position: 'CM', nationality: 'Argentina', age: 25, overall: 85, wage: 150000 },
        { id: 'szoboszlai', name: 'Dominik Szoboszlai', position: 'CM', nationality: 'Hungary', age: 23, overall: 83, wage: 130000 },
        { id: 'gravenberch', name: 'Ryan Gravenberch', position: 'CM', nationality: 'Netherlands', age: 22, overall: 81, wage: 100000 },
        { id: 'salah', name: 'Mohamed Salah', position: 'RW', nationality: 'Egypt', age: 32, overall: 90, wage: 400000 },
        { id: 'jota', name: 'Diogo Jota', position: 'LW', nationality: 'Portugal', age: 28, overall: 85, wage: 150000 },
        { id: 'nunez', name: 'Darwin Núñez', position: 'ST', nationality: 'Uruguay', age: 25, overall: 84, wage: 200000 },
        { id: 'gakpo', name: 'Cody Gakpo', position: 'LW', nationality: 'Netherlands', age: 25, overall: 82, wage: 120000 },
        { id: 'jones_c', name: 'Curtis Jones', position: 'CM', nationality: 'England', age: 23, overall: 78, wage: 70000 },
        { id: 'quansah', name: 'Jarell Quansah', position: 'CB', nationality: 'England', age: 21, overall: 75, wage: 40000 },
        { id: 'tsimikas', name: 'Konstantinos Tsimikas', position: 'LB', nationality: 'Greece', age: 28, overall: 77, wage: 60000 },
        { id: 'chiesa', name: 'Federico Chiesa', position: 'RW', nationality: 'Italy', age: 27, overall: 82, wage: 100000 },
        { id: 'kelleher', name: 'Caoimhin Kelleher', position: 'GK', nationality: 'Ireland', age: 25, overall: 78, wage: 50000 },
        { id: 'endo', name: 'Wataru Endo', position: 'CM', nationality: 'Japan', age: 31, overall: 78, wage: 70000 },
        { id: 'bradley_c', name: 'Conor Bradley', position: 'RB', nationality: 'N. Ireland', age: 21, overall: 77, wage: 40000 },
        { id: 'luiz_a', name: 'Alexis Cabrera', position: 'CB', nationality: 'Argentina', age: 21, overall: 72, wage: 20000 },
        { id: 'morton', name: 'Tyler Morton', position: 'CM', nationality: 'England', age: 22, overall: 73, wage: 25000 },
      ]
    },
    {
      id: 'chelsea',
      name: 'Chelsea',
      shortName: 'Chelsea',
      emoji: '🔵',
      stadium: 'Stamford Bridge',
      manager: 'Enzo Maresca',
      budget: 250000000,
      players: [
        { id: 'sanchez_r', name: 'Robert Sánchez', position: 'GK', nationality: 'Spain', age: 27, overall: 80, wage: 100000 },
        { id: 'james_r', name: 'Reece James', position: 'RB', nationality: 'England', age: 24, overall: 85, wage: 180000 },
        { id: 'thiago_s', name: 'Thiago Silva', position: 'CB', nationality: 'Brazil', age: 40, overall: 82, wage: 120000 },
        { id: 'colwill', name: 'Levi Colwill', position: 'CB', nationality: 'England', age: 21, overall: 79, wage: 80000 },
        { id: 'chilwell', name: 'Ben Chilwell', position: 'LB', nationality: 'England', age: 27, overall: 80, wage: 120000 },
        { id: 'caicedo', name: 'Moisés Caicedo', position: 'CM', nationality: 'Ecuador', age: 22, overall: 83, wage: 150000 },
        { id: 'enzo_f', name: 'Enzo Fernández', position: 'CM', nationality: 'Argentina', age: 23, overall: 83, wage: 200000 },
        { id: 'gallagher', name: 'Conor Gallagher', position: 'CM', nationality: 'England', age: 24, overall: 78, wage: 80000 },
        { id: 'palmer', name: 'Cole Palmer', position: 'CAM', nationality: 'England', age: 22, overall: 87, wage: 150000 },
        { id: 'jackson_n', name: 'Nicolas Jackson', position: 'ST', nationality: 'Senegal', age: 23, overall: 80, wage: 100000 },
        { id: 'sterling', name: 'Raheem Sterling', position: 'LW', nationality: 'England', age: 29, overall: 81, wage: 300000 },
        { id: 'mudryk', name: 'Mykhailo Mudryk', position: 'LW', nationality: 'Ukraine', age: 23, overall: 78, wage: 120000 },
        { id: 'nkunku', name: 'Christopher Nkunku', position: 'ST', nationality: 'France', age: 26, overall: 83, wage: 180000 },
        { id: 'disasi', name: 'Axel Disasi', position: 'CB', nationality: 'France', age: 26, overall: 78, wage: 80000 },
        { id: 'gusto', name: 'Malo Gusto', position: 'RB', nationality: 'France', age: 21, overall: 78, wage: 80000 },
        { id: 'badiashile', name: 'Benoît Badiashile', position: 'CB', nationality: 'France', age: 23, overall: 78, wage: 80000 },
        { id: 'cucurella', name: 'Marc Cucurella', position: 'LB', nationality: 'Spain', age: 25, overall: 79, wage: 90000 },
        { id: 'madueke', name: 'Noni Madueke', position: 'RW', nationality: 'England', age: 22, overall: 78, wage: 70000 },
        { id: 'fernandez_m', name: 'João Félix', position: 'CAM', nationality: 'Portugal', age: 25, overall: 82, wage: 130000 },
        { id: 'petrovic', name: 'Filip Jörgensen', position: 'GK', nationality: 'Denmark', age: 22, overall: 76, wage: 50000 },
        { id: 'dewsbury', name: 'Myles Dewsbury-Hall', position: 'CM', nationality: 'England', age: 25, overall: 78, wage: 70000 },
      ]
    },
    {
      id: 'tottenham',
      name: 'Tottenham Hotspur',
      shortName: 'Spurs',
      emoji: '⚪',
      stadium: 'Tottenham Hotspur Stadium',
      manager: 'Ange Postecoglou',
      budget: 120000000,
      players: [
        { id: 'vicario', name: 'Guglielmo Vicario', position: 'GK', nationality: 'Italy', age: 28, overall: 83, wage: 100000 },
        { id: 'porro', name: 'Pedro Porro', position: 'RB', nationality: 'Spain', age: 25, overall: 81, wage: 100000 },
        { id: 'romero', name: 'Cristian Romero', position: 'CB', nationality: 'Argentina', age: 26, overall: 84, wage: 130000 },
        { id: 'van_de_ven', name: 'Micky van de Ven', position: 'CB', nationality: 'Netherlands', age: 23, overall: 82, wage: 100000 },
        { id: 'udogie', name: 'Destiny Udogie', position: 'LB', nationality: 'Italy', age: 22, overall: 80, wage: 80000 },
        { id: 'bissouma', name: 'Yves Bissouma', position: 'CM', nationality: 'Mali', age: 28, overall: 80, wage: 90000 },
        { id: 'bentancur', name: 'Rodrigo Bentancur', position: 'CM', nationality: 'Uruguay', age: 27, overall: 80, wage: 90000 },
        { id: 'maddison', name: 'James Maddison', position: 'CAM', nationality: 'England', age: 27, overall: 84, wage: 150000 },
        { id: 'kulusevski', name: 'Dejan Kulusevski', position: 'RW', nationality: 'Sweden', age: 24, overall: 82, wage: 120000 },
        { id: 'son', name: 'Heung-Min Son', position: 'LW', nationality: 'South Korea', age: 32, overall: 85, wage: 200000 },
        { id: 'richarlison', name: 'Richarlison', position: 'ST', nationality: 'Brazil', age: 27, overall: 81, wage: 150000 },
        { id: 'johnson_b', name: 'Brennan Johnson', position: 'RW', nationality: 'Wales', age: 23, overall: 78, wage: 80000 },
        { id: 'sarr', name: 'Pape Matar Sarr', position: 'CM', nationality: 'Senegal', age: 22, overall: 78, wage: 70000 },
        { id: 'skipp', name: 'Oliver Skipp', position: 'CM', nationality: 'England', age: 24, overall: 74, wage: 50000 },
        { id: 'dragusin', name: 'Radu Drăgușin', position: 'CB', nationality: 'Romania', age: 22, overall: 76, wage: 50000 },
        { id: 'forster', name: 'Fraser Forster', position: 'GK', nationality: 'England', age: 36, overall: 72, wage: 40000 },
        { id: 'manor', name: 'Manor Solomon', position: 'LW', nationality: 'Israel', age: 25, overall: 74, wage: 50000 },
        { id: 'spence', name: 'Djed Spence', position: 'RB', nationality: 'England', age: 24, overall: 73, wage: 40000 },
        { id: 'dangos', name: 'Alejo Véliz', position: 'ST', nationality: 'Argentina', age: 21, overall: 71, wage: 30000 },
        { id: 'bergvall', name: 'Lucas Bergvall', position: 'CM', nationality: 'Sweden', age: 18, overall: 72, wage: 20000 },
        { id: 'solanke', name: 'Dominic Solanke', position: 'ST', nationality: 'England', age: 27, overall: 79, wage: 120000 },
      ]
    },
    {
      id: 'man_utd',
      name: 'Manchester United',
      shortName: 'Man Utd',
      emoji: '🔴',
      stadium: 'Old Trafford',
      manager: 'Ruben Amorim',
      budget: 150000000,
      players: [
        { id: 'onana', name: 'André Onana', position: 'GK', nationality: 'Cameroon', age: 28, overall: 83, wage: 120000 },
        { id: 'dalot', name: 'Diogo Dalot', position: 'RB', nationality: 'Portugal', age: 25, overall: 80, wage: 100000 },
        { id: 'varane', name: 'Raphaël Varane', position: 'CB', nationality: 'France', age: 31, overall: 82, wage: 200000 },
        { id: 'maguire', name: 'Harry Maguire', position: 'CB', nationality: 'England', age: 31, overall: 78, wage: 180000 },
        { id: 'shaw', name: 'Luke Shaw', position: 'LB', nationality: 'England', age: 29, overall: 82, wage: 150000 },
        { id: 'casemiro', name: 'Casemiro', position: 'CM', nationality: 'Brazil', age: 32, overall: 83, wage: 300000 },
        { id: 'fernandes_b', name: 'Bruno Fernandes', position: 'CAM', nationality: 'Portugal', age: 30, overall: 86, wage: 250000 },
        { id: 'mainoo', name: 'Kobbie Mainoo', position: 'CM', nationality: 'England', age: 19, overall: 78, wage: 50000 },
        { id: 'rashford', name: 'Marcus Rashford', position: 'LW', nationality: 'England', age: 27, overall: 83, wage: 300000 },
        { id: 'hojlund', name: 'Rasmus Højlund', position: 'ST', nationality: 'Denmark', age: 21, overall: 79, wage: 130000 },
        { id: 'antony', name: 'Antony', position: 'RW', nationality: 'Brazil', age: 24, overall: 77, wage: 200000 },
        { id: 'martial', name: 'Anthony Martial', position: 'ST', nationality: 'France', age: 28, overall: 78, wage: 250000 },
        { id: 'mount', name: 'Mason Mount', position: 'CM', nationality: 'England', age: 25, overall: 79, wage: 200000 },
        { id: 'amrabat', name: 'Sofyan Amrabat', position: 'CM', nationality: 'Morocco', age: 28, overall: 78, wage: 100000 },
        { id: 'lindelof', name: 'Victor Lindelöf', position: 'CB', nationality: 'Sweden', age: 30, overall: 78, wage: 120000 },
        { id: 'evans_j', name: 'Jonny Evans', position: 'CB', nationality: 'N. Ireland', age: 36, overall: 73, wage: 80000 },
        { id: 'reguilon', name: 'Sergio Reguilón', position: 'LB', nationality: 'Spain', age: 27, overall: 76, wage: 80000 },
        { id: 'pellistri', name: 'Facundo Pellistri', position: 'RW', nationality: 'Uruguay', age: 22, overall: 74, wage: 50000 },
        { id: 'forson', name: 'Toby Collyer', position: 'CM', nationality: 'England', age: 20, overall: 70, wage: 20000 },
        { id: 'heaton', name: 'Tom Heaton', position: 'GK', nationality: 'England', age: 38, overall: 72, wage: 50000 },
        { id: 'eriksen', name: 'Christian Eriksen', position: 'CAM', nationality: 'Denmark', age: 32, overall: 80, wage: 150000 },
      ]
    },
  ]
};

module.exports = premierLeague;
